name: Test Sourcemod compilation

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Set environment variables
        run: echo SCRIPTS_PATH=$(pwd) >> $GITHUB_ENV

      - name: Setup SourcePawn Compiler ${{ matrix.SM_VERSION }}
        id: setup_sp
        uses: rumblefrog/setup-sp@master
        with:
          version: "1.11.x"
          version-file: ./scripting/TF2-UnhardcodedBleedDurationOnProjectiles.sp

      - name: Download SourcePawn plugin dependencies
        uses: Zabaniya001/SPDependy@v1
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
  
      - name: Compile plugins
        run: |
          mkdir plugins
          spcomp -w234 -O2 -v2 -i"scripting/include" -i".temp/include" -o"plugins/TF2-UnhardcodedBleedDurationOnProjectiles.smx" scripting/TF2-UnhardcodedBleedDurationOnProjectiles.sp
        working-directory: ${{ env.SCRIPTS_PATH }}